<?php

/**
 * Implements hook_permission().
 */
function ticket_permission() {
  $permissions = array(
    'administer ticket entities' => array(
      'title' => t('Administer ticket entities'),
    ),
    'create ticket entity' => array(
      'title' => t('Create ticket entities'),
    ),
    'view ticket entity' => array(
      'title' => t('View ticket entity'),
    ),
    'edit ticket entity' => array(
      'title' => t('Edit ticket entity'),
    ),
    'delete ticket entity' => array(
      'title' => t('Delete ticket entity'),
    ),
  );
  return $permissions;
}


/**
 * Implements hook_menu().
 */
function ticket_menu() {
  $items['admin/structure/tickets/manage'] = array(
    'title' => 'Tickets',
    'description' => 'Administer Ticket entity type',
    'page callback' => 'ticket_list_entities',
    'access arguments' => array('administer ticket entities'),
  );

  $items['admin/structure/tickets/manage/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $items['admin/structure/tickets/manage/add'] = array(
    'title' => 'Add a Ticket',
    'page callback' => 'ticket_add',
    'access arguments' => array('create ticket entity'),
    'type' => MENU_LOCAL_ACTION,
  );

  // Add example entities.
  //$items['ticket/get'] = array(
  //  'title' => 'Request a ticket',
  //  'page callback' => 'ticket_get',
  //  'access arguments' => array('create ticket entity'),
  //);

  $items['ticket/%ticket'] = array(
    'title callback' => 'ticket_title',
    'title arguments' => array(1),
    'page callback' => 'ticket_view',
    'page arguments' => array(1),
    'access arguments' => array('view ticket entity'),
  );

    // 'View' tab for an individual entity page.
  $items['ticket/%ticket/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  // 'Edit' tab for an individual entity page.
  $items['ticket/%ticket/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ticket_form', 1),
    'access arguments' => array('edit ticket entity'),
    'type' => MENU_LOCAL_TASK,
  );

  $items['ticket/%ticket/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ticket_delete_form', 1),
    'access arguments' => array('delete ticket entity'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}


function ticket_entity_info() {
  $info['ticket'] = array(
    'label' => t('Ticket'),
    'controller class' => 'TicketController',
    'base table' => 'ticket',
    'uri callback' => 'ticket_uri',
    'fieldable' => TRUE,
    'entity keys' => array(
      'id' => 'tid' ,
    ),
    'bundle keys' => array(
    ),
    'static cache' => TRUE,
    'bundles' => array(
      'ticket' => array(
        'label' => 'Standard Ticket',
        'admin' => array(
          'path' => 'admin/structure/tickets/manage',
          'access arguments' => array('administer ticket entities'),
        ),
      ),
    ),
    'view modes' => array(
      'full' => array(
        'label' => t('Full'),
      ),
      'short' => array(
        'label' => t('Short'),
      ),
    ),
  );

  return $info;
}

function ticket_field_extra_fields() {
  $form_elements['seats'] = array(
    'label' => t('Number of seats'),
    'weight' => 0,
  );

  $display_elements['seats'] = array(
    'label' => t('Number of seats'),
    'weight' => 0,
  );

  $extra_fields['ticket']['ticket']['form'] = $form_elements;
  $extra_fields['ticket']['ticket']['display'] = $display_elements;

  return $extra_fields;
}

function ticket_list_entities() {
  $content = array();
  // Load all of our entities.
  $entities = ticket_load_multiple();

  $destination = drupal_get_destination();

  if (!empty($entities)) {
    foreach ($entities as $entity) {
      // Create tabular rows for our entities.
      $rows[] = array(
        'data' => array(
          'id' => $entity->tid,
          'seats' => $entity->seats,
          'operations' => array(
            'data' => array(
              '#type' => 'link',
              '#title' => t('edit'),
              '#href' => "ticket/$entity->tid/edit",
              '#options' => array('query' => $destination)
            )
          ),
        ),
      );
    }

    // Put our entities into a themed table. See theme_table() for details.
    $content['entity_table'] = array(
      '#theme' => 'table',
      '#rows' => $rows,
      '#header' => array(t('ID'), t('Num of Seats'), t('Operations')),
    );
  }

  else {
    // There were no entities. Tell the user.
    $content[] = array(
      '#type' => 'item',
      '#markup' => t('There are no tickets.'),
    );
  }

  return $content;
}

function ticket_load($id = NULL, $reset = FALSE) {
  $ids = (isset($id) ? array($id) : array());
  $tickets = ticket_load_multiple($ids, array(), $reset);
  return $tickets ? reset($tickets) : FALSE;
}

function ticket_load_multiple($ids = FALSE, $conditions = array(), $reset = FALSE) {
  return entity_load('ticket', $ids, $conditions, $reset);
}

function ticket_save(&$entity) {
  return entity_get_controller('ticket')->save($entity);
}

function ticket_uri($ticket) {
  return array(
    'path' => 'ticket/' . $ticket->tid,
  );
}

function ticket_add() {
  $entity = entity_get_controller('ticket')->create();
  return drupal_get_form('ticket_form', $entity);
}

function ticket_form($form, &$form_state, $entity) {
  $form['seats'] = array(
    '#type' => 'textfield',
    '#title' => t('Seats'),
    '#required' => TRUE,
    '#default_value' => $entity->seats,
  );

  $form['#entity'] = array(
    '#type' => 'value',
    '#value' => $entity,
  );

  $form_state['ticket'] = $entity;

  field_attach_form('ticket', $entity, $form, $form_state);

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
    '#weight' => 100,
  );

  return $form;
}

//ticket_form_validate
function ticket_form_validate($form, &$form_state) {
  field_attach_form_validate('ticket', $form_state['ticket'], $form, $form_state);
}

//ticket_form_submit
function ticket_form_submit($form, &$form_state) {
  $entity = $form_state['ticket'];

  entity_form_submit_build_entity('ticket', $entity, $form, $form_state);

  $entity = ticket_save($entity);

  // $form_state['redirect'] = 'examples/entity_example/basic/' . $entity->basic_id;
  // $form_state['redirect'] = 'admin/structure/tickets/manage';
}

function ticket_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return 'plugins/content_types';
  }
}

/**
 * Defines an array for hook_views_api().
 */
function ticket_views_api() {
  return array(
    'api' => '3.0',
    'path' => drupal_get_path('module', 'ticket') . '/views',
    'template path' => drupal_get_path('module', 'ticket') . '/templates',
  );
}

/**
 * Implements hook_views_data().
 */
function ticket_views_data() {
  $data['ticket']['table']['group'] = t('Ticket');

  $data['ticket']['table']['base'] = array(
    'field' => 'tid',
    'title' => t('Ticket'),
    'weight' => -10,
    'access query tag' => 'entity_access',
    'defaults' => array(
      'field' => 'tid',
    ),
  );
  $data['ticket']['table']['entity type'] = 'ticket';

  // ----------------------------------------------------------------
  // entity table -- fields
  // tid
  $data['ticket']['tid'] = array(
    'title' => t('ID'),
    'help' => t('The ticket ID.'), // The help that appears on the UI,
    // Information for displaying the nid
    'field' => array(
      'handler' => 'views_handler_field_ticket',
      'click sortable' => TRUE,
    ),
    // Information for accepting a nid as a filter
    'filter' => array(
      'handler' => 'views_handler_filter_numeric',
    ),
    // Information for sorting on a nid.
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
  );

  $data['ticket']['seats'] = array(
    'title' => t('Number of seats'),
    'help' => t('Number of seats.'), // The help that appears on the UI,
    // Information for displaying the nid
    'field' => array(
      'handler' => 'views_handler_field_numeric',
      'click sortable' => TRUE,
    ),
    // Information for accepting a nid as a filter
    'filter' => array(
      'handler' => 'views_handler_filter_numeric',
    ),
    // Information for sorting on a nid.
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
  );

  return $data;
}


